# Generated by Django 4.2.1 on 2023-05-22 11:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodels",
            name="blog_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
