# Generated by Django 4.2.1 on 2023-05-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0002_alter_blogmodels_blog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodels",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images"),
        ),
    ]
