# Generated by Django 4.2.1 on 2023-05-23 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_blogmodels_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodels",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="blog_images"
            ),
            preserve_default=False,
        ),
    ]
