# Generated by Django 4.2.1 on 2023-05-25 07:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0005_alter_blogmodels_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodels",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="blog_title",
                unique=True,
            ),
        ),
    ]
